In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv(r'C:\Users\Rishi\Downloads\country.csv')
data

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34.0,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9.0,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,49,2.7,-99,-99,-99,-99,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1.0,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21.0,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13.0,...,16.4,89,37.2,12.0/0.8,482,30,97.0/67.3,49.3/30.8,6.00,-99

In [4]:
data.shape

(229, 50)

In [ ]:
pd.set_option('display.max_columns', None)

In [6]:
data.head()

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),Economy: Industry (% of GVA),Economy: Services and other activity (% of GVA),Employment: Agriculture (% of employed),Employment: Industry (% of employed),Employment: Services (% of employed),Unemployment (% of labour force),Labour force participation (female/male pop. %),Agricultural production index (2004-2006=100),Food production index (2004-2006=100),International trade: Exports (million US$),International trade: Imports (million US$),International trade: Balance (million US$),"Balance of payments, current account (million US$)",Population growth rate (average annual %),Urban population (% of total population),Urban population growth rate (average annual %),"Fertility rate, total (live births per woman)","Life expectancy at birth (females/males, years)","Population age distribution (0-14 / 60+ years, %)",International migrant stock (000/% of total pop.),Refugees and others of concern to UNHCR (in thousands),Infant mortality rate (per 1000 live births,Health: Total expenditure (% of GDP),Health: Physicians (per 1000 pop.),Education: Government expenditure (% of GDP),Education: Primary gross enrol. ratio (f/m per 100 pop.),Education: Secondary gross enrol. ratio (f/m per 100 pop.),Education: Tertiary gross enrol. ratio (f/m per 100 pop.),Seats held by women in national parliaments %,Mobile-cellular subscriptions (per 100 inhabitants),Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,23.3,53.3,61.6,10.0,28.5,8.6,19.3/83.6,125,125,1458,3568,-2110,-5121,3.2,26.7,4.0,5.3,63.5/61.0,43.2/4.1,382.4/1.2,1513.1,68.6,8.2,0.3,3.3,91.1/131.6,39.7/70.7,3.7/13.3,27.7,61.6,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,26.0,51.7,41.4,18.3,40.3,15.8,40.2/61.0,134,134,1962,4669,-2707,-1222,-0.1,57.4,2.2,1.7,79.9/75.6,17.4/19.0,57.6/2.0,8.8,14.6,5.9,1.3,3.5,111.7/115.5,92.5/98.8,68.1/48.7,22.9,106.4,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,37.3,50.5,10.8,34.5,54.7,11.4,17.0/70.7,160,161,29992,47091,-17099,-27229,2.0,70.7,2.8,3.0,76.5/74.1,29.3/9.4,242.4/0.6,99.8,27.7,7.2,...,...,112.7/119.5,101.7/98.1,45.1/28.9,31.6,113.0,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,-99.0,-99.0,...,...,...,...,.../...,112,112,-99,-99,-99,-99,-~0.0,87.2,-0.1,2.6,77.8/71.1,33.3/9.0,23.2/41.8,-99,9.6,-99.0,-99,-99,-99,-99,-99,-99.0,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,10.8,88.6,-99,-99,-99,-99,-99,-99,-99,100,1355,-1255,-99,-1.6,85.1,0.1,1.2,-99,14.4/19.0,42.1/59.7,-99,-99,8.1,3.7,3.3,-99,-99,-99,32.1,88.1,96.9,13,34.0,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99

In [7]:
data.info() #summary of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 50 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   country                                                     229 non-null    object
 1   Region                                                      229 non-null    object
 2   Surface area (km2)                                          229 non-null    object
 3   Population in thousands (2017)                              229 non-null    int64
 4   Population density (per km2, 2017)                          229 non-null    float64
 5   Sex ratio (m per 100 f, 2017)                               229 non-null    float64
 6   GDP: Gross domestic product (million current US$)           229 non-null    int64
 7   GDP growth rate (annual %, const. 2005 prices)              229 non-null    object
 8   GDP per capita (current US$)                                229 non-null    float64
 9   Economy: Agriculture (% of GVA)                             229 non-null    object
 10  Economy: Industry (% of GVA)                                229 non-null    float64
 11  Economy: Services and other activity (% of GVA)             229 non-null    float64
 12  Employment: Agriculture (% of employed)                     229 non-null    object
 13  Employment: Industry (% of employed)                        229 non-null    object
 14  Employment: Services (% of employed)                        229 non-null    object
 15  Unemployment (% of labour force)                            229 non-null    object
 16  Labour force participation (female/male pop. %)             229 non-null    object
 17  Agricultural production index (2004-2006=100)               229 non-null    int64
 18  Food production index (2004-2006=100)                       229 non-null    int64
 19  International trade: Exports (million US$)                  229 non-null    object
 20  International trade: Imports (million US$)                  229 non-null    object
 21  International trade: Balance (million US$)                  229 non-null    object
 22  Balance of payments, current account (million US$)          229 non-null    object
 23  Population growth rate (average annual %)                   229 non-null    object
 24  Urban population (% of total population)                    229 non-null    float64
 25  Urban population growth rate (average annual %)             229 non-null    object
 26  Fertility rate, total (live births per woman)               229 non-null    object
 27  Life expectancy at birth (females/males, years)             229 non-null    object
 28  Population age distribution (0-14 / 60+ years, %)           229 non-null    object
 29  International migrant stock (000/% of total pop.)           229 non-null    object
 30  Refugees and others of concern to UNHCR (in thousands)      229 non-null    object
 31  Infant mortality rate (per 1000 live births                 229 non-null    object
 32  Health: Total expenditure (% of GDP)                        229 non-null    float64
 33  Health: Physicians (per 1000 pop.)                          229 non-null    object
 34  Education: Government expenditure (% of GDP)                229 non-null    object
 35  Education: Primary gross enrol. ratio (f/m per 100 pop.)    229 non-null    object
 36  Education: Secondary gross enrol. ratio (f/m per 100 pop.)  229 non-null    object
 37  Education: Tertiary gross enrol. ratio (f/m per 100 pop.)   229 non-null    object
 38  Seats held by women in national parliaments %               229 non-null    float64
 39  Mobile-cellular subscriptions (per 100 inhabitants)         229 non-null    object
 40  Mobile-cellular subscriptions (per 100 inhabitants).1       229 non-null    object
 41  Individuals using the Internet (per 100 inhabitants)        229 non-null    int64
 42  Threatened species (number)                                 229 non-null    object
 43  Forested area (% of land area)                              229 non-null    object
 44  CO2 emission estimates (million tons/tons per capita)       229 non-null    int64
 45  Energy production, primary (Petajoules)                     229 non-null    int64
 46  Energy supply per capita (Gigajoules)                       229 non-null    object
 47  Pop. using improved drinking water (urban/rural, %)         229 non-null    object
 48  Pop. using improved sanitation facilities (urban/rural, %)  229 non-null    object
 49  Net Official Development Assist. received (% of GNI)        229 non-null    int64
dtypes: float64(8), int64(8), object(34)
memory usage: 89.6+ KB

In [8]:
#checking the null values
data.isnull().sum()

country                                                       0
Region                                                        0
Surface area (km2)                                            0
Population in thousands (2017)                                0
Population density (per km2, 2017)                            0
Sex ratio (m per 100 f, 2017)                                 0
GDP: Gross domestic product (million current US$)             0
GDP growth rate (annual %, const. 2005 prices)                0
GDP per capita (current US$)                                  0
Economy: Agriculture (% of GVA)                               0
Economy: Industry (% of GVA)                                  0
Economy: Services and other activity (% of GVA)               0
Employment: Agriculture (% of employed)                       0
Employment: Industry (% of employed)                          0
Employment: Services (% of employed)                          0
Unemployment (% of labour force)                              0
Labour force participation (female/male pop. %)               0
Agricultural production index (2004-2006=100)                 0
Food production index (2004-2006=100)                         0
International trade: Exports (million US$)                    0
International trade: Imports (million US$)                    0
International trade: Balance (million US$)                    0
Balance of payments, current account (million US$)            0
Population growth rate (average annual %)                     0
Urban population (% of total population)                      0
Urban population growth rate (average annual %)               0
Fertility rate, total (live births per woman)                 0
Life expectancy at birth (females/males, years)               0
Population age distribution (0-14 / 60+ years, %)             0
International migrant stock (000/% of total pop.)             0
Refugees and others of concern to UNHCR (in thousands)        0
Infant mortality rate (per 1000 live births                   0
Health: Total expenditure (% of GDP)                          0
Health: Physicians (per 1000 pop.)                            0
Education: Government expenditure (% of GDP)                  0
Education: Primary gross enrol. ratio (f/m per 100 pop.)      0
Education: Secondary gross enrol. ratio (f/m per 100 pop.)    0
Education: Tertiary gross enrol. ratio (f/m per 100 pop.)     0
Seats held by women in national parliaments %                 0
Mobile-cellular subscriptions (per 100 inhabitants)           0
Mobile-cellular subscriptions (per 100 inhabitants).1         0
Individuals using the Internet (per 100 inhabitants)          0
Threatened species (number)                                   0
Forested area (% of land area)                                0
CO2 emission estimates (million tons/tons per capita)         0
Energy production, primary (Petajoules)                       0
Energy supply per capita (Gigajoules)                         0
Pop. using improved drinking water (urban/rural, %)           0
Pop. using improved sanitation facilities (urban/rural, %)    0
Net Official Development Assist. received (% of GNI)          0
dtype: int64

# Key Elements of Descriptive Statistics

### Measures Of Central Tendency

* Mean
* Median
* Mode

### Measures Of Spread

* Range
* Outliers
* Interquantile Range
* Variance
* Standard deviation

### Dependence

* Correlation

# we will begin our initial descriptive statistical analysis.

For our analysis, we will chosen 'Population in thousands (2017)' column. We can perform the similar operations on other columns as well. We will get the measure of central tendency and measure of spread of the data.

In [10]:
# mean

# Manually
data['Population in thousands (2017)'].sum()/len(data['Population in thousands (2017)'])

32756.794759825327

In [11]:
#mean - we will check the mean of the Population in thousands (2017)
data['Population in thousands (2017)'].mean()

32756.794759825327

In [12]:
#median - we will check the median of the Population in thousands (2017)
data['Population in thousands (2017)'].median()

5448.0

In [13]:
#mode - we will check the mode of the Population in thousands (2017)
data['Population in thousands (2017)'].mode()

0        1
1       11
2       35
3       55
4       56
5      105
6      108
7      276
8      283
9     2890
10    2930
Name: Population in thousands (2017), dtype: int64

In [14]:
data['Population in thousands (2017)'].mode()[3] #if you want to excess one value

55

In [15]:
# Range : max - min

a = data['Population in thousands (2017)'].max()
b = data['Population in thousands (2017)'].min()

print("Max value : ", a)
print("Min value: ", b)

Max value :  1409517
Min value:  1

In [16]:
range = a - b
range

1409516

In [17]:
#variance
variance = data['Population in thousands (2017)'].var()

In [18]:
#standard Deviation
data['Population in thousands (2017)'].std()

133275.07991351312

In [19]:
# Manual Std
import math
std_deviation = math.sqrt(variance)
std_deviation

133275.07991351312

In [20]:
# Percentile

#75, 50 and 25 percentile
import numpy as np

sev = np.percentile(data['Population in thousands (2017)'], 75)
fif = np.percentile(data['Population in thousands (2017)'], 50)
twe = np.percentile(data['Population in thousands (2017)'], 25)

print("75th Percentile is : ", sev)
print("50th Percentile is : " , fif)
print("25th Percentile is : ", twe)

75th Percentile is :  19193.0
50th Percentile is :  5448.0
25th Percentile is :  431.0

In [21]:
# Quantile

# Quartile

q1 = data['Population in thousands (2017)'].quantile(0.25)
q2 = data['Population in thousands (2017)'].quantile(0.50)
q3 = data['Population in thousands (2017)'].quantile(0.75)

print(q1,q2,q3)

431.0 5448.0 19193.0

In [22]:
# IQR

iqr = q3 - q1
iqr

18762.0

In [23]:
# correlation
# positive, negative, zero

data["Population in thousands (2017)"].corr(data["Population density (per km2, 2017)"])

-0.025049880150796396

In [26]:
# # vis

# plt.figure(figsize = (15,10))

# sns.heatmap(data.corr(), annot = True)